# Generated by Django 6.0.5 on 2026-05-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_subscribed',
            field=models.BooleanField(default=True),
        ),
    ]
