# Generated by Django 6.0.5 on 2026-05-11 19:19

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SMTPServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., SendGrid Primary', max_length=100)),
                ('host', models.CharField(max_length=255)),
                ('port', models.PositiveIntegerField(default=587)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('use_tls', models.BooleanField(default=True)),
                ('use_ssl', models.BooleanField(default=False)),
                ('from_email', models.EmailField(max_length=254)),
                ('from_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('failed', 'Failed')], default='active', max_length=10)),
                ('priority', models.PositiveSmallIntegerField(default=100)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('last_health_check', models.DateTimeField(blank=True, null=True)),
                ('health_check_passed', models.BooleanField(default=True)),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
                ('daily_limit', models.PositiveIntegerField(default=0, help_text='0 = unlimited')),
                ('sent_today', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smtp_servers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['priority', 'last_used'],
            },
        ),
        migrations.CreateModel(
            name='EmailQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('to_email', models.EmailField(max_length=254)),
                ('to_name', models.CharField(blank=True, max_length=255)),
                ('subject', models.CharField(max_length=998)),
                ('html_content', models.TextField()),
                ('text_content', models.TextField(blank=True)),
                ('priority', models.PositiveSmallIntegerField(choices=[(1, 'High'), (2, 'Normal'), (3, 'Low')], default=2)),
                ('scheduled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('retry', 'Retry')], default='pending', max_length=10)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('max_retries', models.PositiveSmallIntegerField(default=3)),
                ('last_error', models.TextField(blank=True)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('inline_images', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='campaigns.campaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_queue', to=settings.AUTH_USER_MODEL)),
                ('smtp_server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='email_engine.smtpserver')),
            ],
            options={
                'ordering': ['priority', 'scheduled_at'],
                'indexes': [models.Index(fields=['status', 'scheduled_at'], name='email_engin_status_9d7754_idx'), models.Index(fields=['user', 'status'], name='email_engin_user_id_963164_idx')],
            },
        ),
    ]
